---
  title: "Data Analysis Project"
output: html_notebook
---

```{r}
# Load libraries!
library(tidyverse)
library(janitor)
library(ggplot2)

options(scipen=999)
```

```{r}
md_payments <- read_csv("data/State_of_Maryland_Payments_Data__FY2008_to_FY2024.csv") |> clean_names()

view(md_payments)

# The data frame has 430584 rows and 8 columns

# One limitation is that it might be difficult to define each industry just based on agency, and we do not know what each code in the category column means or stands for. In terms sof timeframe, we do not have limitations as our data spans from 2008 to 2024.

```

```{r}
### Question 1: How does the distribution of spending change from year to year?


# Fiscal 2023 saw the highest spending from the Maryland government with $193,756,398,403 paid.
# Fiscal 2022 was $36,656,748,838	

md_payments_by_year <- md_payments |>
  group_by(fiscal_year) |>
  summarise(total = sum(amount)) |>
  arrange(desc(total)) 

md_payments |>
  filter(fiscal_year == 2024) |>
  arrange(desc(amount)) 

md_payments |>
  filter(fiscal_year == 2023) |>
  arrange(desc(amount)) 

#looking at just the payments in fiscal 2023, sorted from highest to lowest, payments are repeated five times so they are counted five times, which is why the total money seems to be so high. The agency name, vendor name and amount are the exact same, and each is repeated the same amount so we believe this is a data entry error that made its way into the dataset.

md_payments |>
  filter(fiscal_year == 2023) |>
  arrange(desc(amount))


payments_minus_2023_24 <- md_payments |>
  filter(!fiscal_year == 2023) |>
  filter(!fiscal_year == 2024) |>
  group_by(fiscal_year) |>
  summarise(total = sum(amount)) |>
  arrange(desc(total)) 

payments_minus_2023_24

#here, we filtered for every year except for 2023 which had the error in the data to then visualize how spending changed from year to year. We also took out fiscal 2024 because the fiscal year has not ended yet.

payments_minus_2023_24 |>
  ggplot() + 
  geom_line(aes(x=fiscal_year, y=total)) +
  labs(
    title = "Total Money Spent by State of Maryland per Fiscal Year",
    x = "Fiscal Year",
    y = "Total Amount",
    caption = "source: Maryland State Payments Data") 


```

```{r}
### Question 2: Which industries spent the most money?

#Payments by industry

#Health
industry_data_health <- md_payments |>
  filter(str_detect(agency_name, "HEALTH")) |>
  group_by(fiscal_year) |>
  summarise(total_health = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "HEALTH")) |>
  count(agency_name)

#Education

industry_data_education <- md_payments |>
  filter(str_detect(agency_name, "EDUCATION") | str_detect(agency_name, "SCHOOL")) |>
  group_by(fiscal_year) |>
  summarise(total_education = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "EDUCATION") | str_detect(agency_name, "SCHOOL")) |>
  count(agency_name)

#Housing

industry_data_housing <- md_payments |>
  filter(str_detect(agency_name, "HOUSING")) |>
  group_by(fiscal_year) |>
  summarise(total_housing = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "HOUSING")) |>
  count(agency_name)

#Crime
industry_data_crime <- md_payments |>

  filter(str_detect(agency_name, "POLICE") | str_detect(agency_name, "CRIME") | str_detect(agency_name, "SAFETY")) |>
  group_by(fiscal_year) |>
  summarise(total_crime = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "POLICE") | str_detect(agency_name, "CRIME") | str_detect(agency_name, "SAFETY")) |>
  count(agency_name)

#Labor

industry_data_labor <- md_payments |>
  filter(str_detect(agency_name, "LABOR")) |>
  group_by(fiscal_year) |>
  summarise(total_labor = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "LABOR")) |>
  count(agency_name)

#Environment

industry_data_environment <- md_payments |>
  filter(str_detect(agency_name, "ENVIRONMENT") | str_detect(agency_name, "AGRICULTURE")) |>
  group_by(fiscal_year) |>
  summarise(total_environment = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "ENVIRONMENT") | str_detect(agency_name, "AGRICULTURE")) |>
  count(agency_name)

#Commerce

industry_data_commerce <- md_payments |>
  filter(str_detect(agency_name, "COMMERCE") | str_detect(agency_name, "COMPTROLLER")) |>
  group_by(fiscal_year) |>
  summarise(total_commerce = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "COMMERCE") | str_detect(agency_name, "COMPTROLLER")) |>
  count(agency_name)

#Transportation
industry_data_transportation <- md_payments |>

  filter(str_detect(agency_name, "HIGH") | str_detect(agency_name, "TRANS") | str_detect(agency_name, "MDOT")) |>
  group_by(fiscal_year) |>
  summarise(total_transportation = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "HIGH") | str_detect(agency_name, "TRANS") | str_detect(agency_name, "MDOT")) |>
  count(agency_name)

#combine them all

all_industry_data <- industry_data_commerce |>
    inner_join(industry_data_crime, by = 'fiscal_year') |>
    inner_join(industry_data_education, by = 'fiscal_year') |>
    inner_join(industry_data_environment, by = 'fiscal_year') |>
    inner_join(industry_data_health, by = 'fiscal_year') |>
    inner_join(industry_data_housing, by = 'fiscal_year') |>
    inner_join(industry_data_labor, by = 'fiscal_year') |>
    inner_join(industry_data_transportation, by = 'fiscal_year')

```

```{r}
### Question 3: What counties or zip codes receive the most money?

# ACS data for total population for each zipcode
md_zip_population <- get_acs(geography = "zcta",
              variables = c(population = "B01001_001"),
              year = 2019,
              state = "MD")

# Filtering md_payments to match the ZCTA data
md_payments_2019 <- md_payments |>
  filter(fiscal_year=="2019")|>
  group_by(vendor_zip)|>
  summarize(amount=sum(amount))|>
  arrange(desc(amount))

# Joining the md_payments with ZCTA data
md_payments_2019 <- md_payments_2019 |>
  inner_join(md_zip_population, by=c('vendor_zip'='GEOID'))

md_payments_2019 <- md_payments_2019 |>
  mutate(rate = estimate/amount*100)

#The rate showed the money spent by the State of Maryland in relation to the population of a given zipcode. But this did not show us much.

md_payments_2019

#We used 2019 data as that is the only year that we also had population data for. The zipcode that the State of Maryland gave the most money to was 21202, which is in Baltimore.

md_payments |>
  filter(vendor_zip == 21202) |>
  arrange(desc(amount))
  
#The highest payments in this zipcode overwhelmingly went to Baltimore City Public Schools from the Maryland State Department of Education.
``
```

```{r}
### Question 4: Where are lower payments going compared to higher one?
md_payments_low <- md_payments |>
  filter(amount < 100) |>
  rename(amount_low = amount)

md_payments_low |>
  group_by(agency_name) |>
  summarise(vendor_name, amount_low, count=n()) |>
  arrange(desc(count))

#The Maryland State Department of Education paid the most payments under $100, as it had a count of 4383 'low' payments

md_payments_high <- md_payments |>
  filter(amount > 1000000) |>
  rename(amount_high = amount)

md_payments_high |> 
  group_by(agency_name) |>
  summarise(vendor_name, amount_high, count=n()) |>
  arrange(desc(count))

# The Maryland Department of Health, on the other hand, had the most payments above $1,000,000, with 5330 'high' payments.
  

```

```{r}
### Question 5: What types of payments are going to education? Are there differences in which systems recieve more/less money

#Using our data of each sector, we focused on education spending to see which agencies recieved the most money and how spending changed over time specifically within education.

industry_data_education <- md_payments |>
  filter(str_detect(agency_name, "EDUCATION") | str_detect(agency_name, "SCHOOL")) |>
  group_by(fiscal_year) |>
  summarise(total_education = sum(amount))

md_payments |>
  filter(str_detect(agency_name, "EDUCATION") | str_detect(agency_name, "SCHOOL")) |>
  count(agency_name)


md_payments |>
  filter(str_detect(agency_name, "EDUCATION") | str_detect(agency_name, "SCHOOL")) |>
  arrange(desc(amount))

#When we arrange the payments from the education department from highest to lowest, the highest payment went to the Mount Rainier Police Department, which could be something to look into. After this, Baltimore City Public Schools recieved the next highest payment followed by the Prince George's County Board of Education and Prince George's County Public Schools. We noticed Overlea High School in Baltimore County was one of the few schools that recieved such a high payment as opposed to the districts.

```
